plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

group 'co.modestnerd.wa_me'
version '1.0-SNAPSHOT'

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

android {
    if (project.android.hasProperty("namespace")) {
        namespace = "co.modestnerd.wa_me"
    }

    compileSdk = 34

    defaultConfig {
        minSdkVersion 21
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lint {
        disable 'InvalidPackage'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    api 'commons-io:commons-io:2.16.1'
    implementation 'androidx.core:core:1.13.1'
}
